name: GPA Monitor

on:
  schedule:
    - cron: '*/3 * * * *'  # كل 3 دقائق
  workflow_dispatch:  # تشغيل يدوي

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests==2.31.0
    
    - name: Run GPA monitor
      env:
        TELEGRAM_BOT_TOKEN: "7680451124:AAFGU99rxasd99ZbyaRxkbbV85tg2yKfG6o"
        TELEGRAM_CHAT_ID: "5824638955"
      run: python gpa.py
